version: '3'
services:
  client:
    build:
      context: ./client
    image: client:dev
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
  server:
    build:
      context: ./server
    image: server:dev
    container_name: backend
    ports:
      - 4000:4000
    volumes:
      - ./server:/app
